language: android
dist: precise
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - george-edison55-precise-backports
    packages:
      - gcc-5
      - g++-5
      - cmake-data
      - cmake
before_script:
  # node stuff
  - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.1/install.sh | bash
  - nvm install 8
  - node --version
  - npm --version

  - echo $CC
  - echo $CXX
  - CC=clang-5.0 CXX=clang++-5.0 npm install opencv4nodejs
script:
  - npm ls opencv4nodejs
