language: android
dist: precise
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-5.0
    packages:
      - g++-4.9
      - clang-5.0
before_script:
  # node stuff
  - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.1/install.sh | bash
  - nvm install 8
  - node --version
  - npm --version

  - echo $CC
  - echo $CXX
  - sudo add-apt-repository ppa:smspillaz/cmake-2.8.12 --yes
  - sudo apt-get update -q
  - sudo apt-get install cmake-data -y
  # - sudo apt-get install cmake -y
  - cmake --version
  - CC=gcc-4.9 CXX=g++-4.9 npm install opencv4nodejs
script:
  - npm ls opencv4nodejs
